---
- hosts: fortigates
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "Mentioned the VDOM Name in which want to Land"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      access_token: "{{ fortios_access_token }}" #access token variable which will be reffered from your host file.
      system_global:
        admintimeout: "23"
        hostname: "FortiGate11"
        admin_lockout_threshold: "8"
        admin_login_max: "9"
